### ISSUE TITLE
GUI, modularize into scenes

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#13]
@Aranior 
Great job on GUI, just some suggestions:
A stage is basically a separate windows so right now you are creating tons of windows. A more correct way would be to just use a stage if you really want a separate window to pop up.
If you just want to switch between menus without dissolving/rebuilding an entire window the following approach would be easier:

Define one "main" stage that has some sort of change scene functionality.
Define a new package called gui.menus gui.scenes or whatever.
Define all menus that can be shown in the same window (eg existing profile/ new profile) as extending scene, not stage.
Simply set the scene shown in the main stage as a new instance of the relevant scene.
Not only does this prevent the window from disappearing when changing menus, it also saves you tons of unnecessary code.

**Comment by Aranior** [comment]
I also thought about this. I didn't really come up with a solution yet, but I'm going to work on it, when I am back home on Sunday. For the new Profile and the Statistics window however I think it is okay to open up a new Window as discussed on Tuesday. But you are right about the rest. (Mainly the 3 Menus leading up to the Main Program)

**Comment by xxxFourierxxx** [comment]
I just added a commit that started the refactoring process, I didn't "convert" all menus yet as I wasn't sure which ones you wanted as separate windows. Check it out m8!
