### ISSUE TITLE
Double MainMenu

### ISSUE THREAD

**Issue by faweizz** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#14]
At the startup a MainMenu is created. It also apprears when you click the hint.

**Comment by Aranior** [comment]
I don't manage to replicate this bug somehow and after analyzing my code cannot see how this has happened to you. We can figure it out tomorrow.

**Comment by xxxFourierxxx** [comment]
Maybe you had two instances of the program open, happens fast esp. with eclipse? Try to replicate the bug again pls
