### ISSUE TITLE
Collect TODO: markers in eclipse and post on issue tracker

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#15]
don't feel like doing this, so we should streamline our issues, if someone could collect the eclipse TODO: marker task list and post it on here it would be helpful

**Comment by Aranior** [comment]
I could do this, but I need to fix my program first as it doesnt work anymore since like 2 pm

**Comment by Aranior** [comment]
Should I open up a new Issue for every single TODO or bundle them together?

**Comment by xxxFourierxxx** [comment]
Single issues I guess are better, also if you are on it delete the in-code markers, ty

**Comment by Aranior** [comment]
I collected most of the markers. but not all of them. Some are hard to add to the bugtracker or are very simple to resolve.

**Comment by xxxFourierxxx** [comment]
ty, nice work
