### ISSUE TITLE
manual needs to be filled out for existing gui components

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#17]
about time we get started on this,
nobody wants to rush a manual on the last days

**Comment by Aranior** [comment]
Uploading this later today, don't worry.

**Comment by Aranior** [comment]
Manual is kinda finished, might need a bit of polishing and some small changes, but generally it is done, so I'm deleting this issue.
