### ISSUE TITLE
Travis configuration incomplete

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#2]
Travis build system is not working and fails at build due to missing config file

**Comment by xxxFourierxxx** [comment]
Stacktrace: [https://api.travis-ci.org/jobs/139194014/log.txt?deansi=true]

**Comment by n2o** [comment]
Your missing a `build.xml` file in your root directory

**Comment by xxxFourierxxx** [comment]
https://travis-ci.org/ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx/builds/139469593

This one worked btw!

**Comment by n2o** [comment]
You can embed a Travis CI badge to your README.md to show the current build status:
![Travis CI](https://api.travis-ci.org/ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx.svg?branch=master)

The url for your project's master branch is the following:

`https://api.travis-ci.org/ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx.svg?branch=master`

**Comment by xxxFourierxxx** [comment]
Fixed with last commit
