### ISSUE TITLE
The  auto-generated ExerciseReader catch-block should be manually edited

### ISSUE THREAD

**Issue by Aranior** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#21]

**Comment by xxxFourierxxx** [comment]
The other way around I think: The catch block IS auto generated and needs to be manually edited to do something other than just the Eclipse-Auto-Stack-Trace-Printing-Whatever-Thingy

**Comment by Aranior** [comment]
Oh okay
