### ISSUE TITLE
Various bugs in workflow // Editor

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#37]
1.
If you create a test assertEquals(false,true) you have a serious issue. There is no way you could ever let that test be successful by writing code and as you are not allowed to go back you are done.

2.
If you create a test and compiling fails because you test for a variable that is not yet there you should still be able to switch states. Say you write a test assertEquals(1,HackTime.aNumber) and aNumber doesnt exist yet because you plan on writing it you also have a problem.

So we(you lol) need to rethink the workflow and editor functionality

**Comment by faweizz** [comment]
Assigment: "Das Werkzeug erlaubt es dem Nutzer nur den Test zu editieren, bis es genau einen
fehlschlagenden Test gibt oder der Code nicht compiliert"
and
"Das Programm erlaubt es dem Nutzer nun ausschlielich den Code zu modizieren,
bis alle Tests laufen. Alternativ kann der Benutzer zuruck zu RED wechseln. Beim Zuruckwechseln zu den Tests wird der neue Code geloscht"

This is finished
