### ISSUE TITLE
AnalyzeError / ErrorType needs more entries ErrorType need checking

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#46]
Someone really needs to check the error recognizing in AnalyzeError and add more error types!!!
this is highly critical!

**Comment by Tschebyscheff** [comment]
error recognizing in AnalyzeError was already checked a long time ago.
statistic scene rdy, so we dont need more error types
