### ISSUE TITLE
Need to create css and streamline GUI-Style

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#5]
We need to find a  common design/style for the gui-elements to create a coherent appearance.

- The Startup-Notification needs to be styled/ design needs to be improved

**Comment by Aranior** [comment]
I think this can be closed, as I already implemented the css and the GUI-Style is kind of coherent now.
We might change it up a bit, but this issue is unnecessary now.
