### ISSUE TITLE
ProfileStats are only stored for the last time the exercise was run

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#50]
This is ok I guess? or should there be multiple exercise launches stored? I think it would be ok to only show the last launch of the exercise as stats.

**Comment by xxxFourierxxx** [comment]
If we leave it this way it should be mentioned in the manual AND in the menu

**Comment by faweizz** [comment]
I think the most easy way to do it is to make it a feature.
