### ISSUE TITLE
Add all missing javadocs

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#54]
Description	Resource	Path	Location	Type
Javadoc: Missing comment for default declaration	AnalyzedTrackingDataCollectionTests.java	/TDDT/src/test/java/org/xxxmathxxx/tddt/tracking_analysis	line 15	Java Problem
Javadoc: Missing comment for default declaration	AnalyzedTrackingDataCollectionTests.java	/TDDT/src/test/java/org/xxxmathxxx/tddt/tracking_analysis	line 16	Java Problem
Javadoc: Missing comment for default declaration	Hint.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/hints	line 4	Java Problem
Javadoc: Missing comment for default declaration	Hint.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/hints	line 5	Java Problem
Javadoc: Missing comment for default declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 283	Java Problem
Javadoc: Missing comment for default declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 300	Java Problem
Javadoc: Missing comment for default declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 320	Java Problem
Javadoc: Missing comment for default declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 350	Java Problem
Javadoc: Missing comment for default declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 378	Java Problem
Javadoc: Missing comment for default declaration	JTextPaneNoWrap.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/ide	line 51	Java Problem
Javadoc: Missing comment for default declaration	ReversedClockLabel.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 16	Java Problem
Javadoc: Missing comment for default declaration	StatisticsPane.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 168	Java Problem
Javadoc: Missing comment for default declaration	TestEditPane.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/ide	line 11	Java Problem
Javadoc: Missing comment for private declaration	BasicTimer.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/timer	line 46	Java Problem
Javadoc: Missing comment for private declaration	EditPane.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/ide	line 24	Java Problem
Javadoc: Missing comment for private declaration	EditPane.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/ide	line 25	Java Problem
Javadoc: Missing comment for private declaration	EditPane.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/ide	line 27	Java Problem
Javadoc: Missing comment for private declaration	EditPane.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/ide	line 28	Java Problem
Javadoc: Missing comment for private declaration	EditPane.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/ide	line 31	Java Problem
Javadoc: Missing comment for private declaration	EditPane.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/ide	line 33	Java Problem
Javadoc: Missing comment for private declaration	EditPane.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/ide	line 193	Java Problem
Javadoc: Missing comment for private declaration	EditPane.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/ide	line 202	Java Problem
Javadoc: Missing comment for private declaration	Editor.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 29	Java Problem
Javadoc: Missing comment for private declaration	Editor.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 30	Java Problem
Javadoc: Missing comment for private declaration	Editor.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 31	Java Problem
Javadoc: Missing comment for private declaration	Editor.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 32	Java Problem
Javadoc: Missing comment for private declaration	Editor.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 33	Java Problem
Javadoc: Missing comment for private declaration	Editor.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 34	Java Problem
Javadoc: Missing comment for private declaration	Editor.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 37	Java Problem
Javadoc: Missing comment for private declaration	Editor.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 250	Java Problem
Javadoc: Missing comment for private declaration	ErrorCounter.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/tracking_analysis	line 22	Java Problem
Javadoc: Missing comment for private declaration	ExercisePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 31	Java Problem
Javadoc: Missing comment for private declaration	ExercisePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 33	Java Problem
Javadoc: Missing comment for private declaration	ExercisePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 35	Java Problem
Javadoc: Missing comment for private declaration	ExercisePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 37	Java Problem
Javadoc: Missing comment for private declaration	ExercisePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 39	Java Problem
Javadoc: Missing comment for private declaration	ExercisePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 41	Java Problem
Javadoc: Missing comment for private declaration	ExercisePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 43	Java Problem
Javadoc: Missing comment for private declaration	ExerciseReader.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/io	line 19	Java Problem
Javadoc: Missing comment for private declaration	ExerciseReader.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/io	line 20	Java Problem
Javadoc: Missing comment for private declaration	ExerciseReader.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/io	line 29	Java Problem
Javadoc: Missing comment for private declaration	ExistingProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 24	Java Problem
Javadoc: Missing comment for private declaration	ExistingProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 25	Java Problem
Javadoc: Missing comment for private declaration	ExistingProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 26	Java Problem
Javadoc: Missing comment for private declaration	ExistingProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 27	Java Problem
Javadoc: Missing comment for private declaration	ExistingProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 28	Java Problem
Javadoc: Missing comment for private declaration	ExistingProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 29	Java Problem
Javadoc: Missing comment for private declaration	ExistingProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 30	Java Problem
Javadoc: Missing comment for private declaration	GraphicsHelper.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 14	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 48	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 49	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 50	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 51	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 53	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 55	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 57	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 58	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 60	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 61	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 62	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 63	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 65	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 69	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 70	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 72	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 74	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 75	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 75	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 75	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 78	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 80	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 202	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 256	Java Problem
Javadoc: Missing comment for private declaration	ImageCropperTool.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 270	Java Problem
Javadoc: Missing comment for private declaration	NewProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 31	Java Problem
Javadoc: Missing comment for private declaration	NewProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 32	Java Problem
Javadoc: Missing comment for private declaration	NewProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 33	Java Problem
Javadoc: Missing comment for private declaration	NewProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 34	Java Problem
Javadoc: Missing comment for private declaration	NewProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 35	Java Problem
Javadoc: Missing comment for private declaration	NewProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 36	Java Problem
Javadoc: Missing comment for private declaration	NewProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 39	Java Problem
Javadoc: Missing comment for private declaration	NewProfileMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 40	Java Problem
Javadoc: Missing comment for private declaration	ProfilePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 21	Java Problem
Javadoc: Missing comment for private declaration	ProfilePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 24	Java Problem
Javadoc: Missing comment for private declaration	ProfilePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 25	Java Problem
Javadoc: Missing comment for private declaration	ProfilePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 26	Java Problem
Javadoc: Missing comment for private declaration	ProfilePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 28	Java Problem
Javadoc: Missing comment for private declaration	ProfilePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 30	Java Problem
Javadoc: Missing comment for private declaration	ProfilePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 108	Java Problem
Javadoc: Missing comment for private declaration	ProfilePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 126	Java Problem
Javadoc: Missing comment for private declaration	ProfilePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 161	Java Problem
Javadoc: Missing comment for private declaration	ProfilePicker.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 174	Java Problem
Javadoc: Missing comment for private declaration	RestrictedTextField.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 9	Java Problem
Javadoc: Missing comment for private declaration	RestrictedTextField.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 10	Java Problem
Javadoc: Missing comment for private declaration	ReversedClockLabel.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 26	Java Problem
Javadoc: Missing comment for private declaration	ReversedClockLabel.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui	line 33	Java Problem
Javadoc: Missing comment for private declaration	StartupMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 26	Java Problem
Javadoc: Missing comment for private declaration	StartupMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 27	Java Problem
Javadoc: Missing comment for private declaration	StartupMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 28	Java Problem
Javadoc: Missing comment for private declaration	StartupMenu.java	/TDDT/src/main/java/org/xxxmathxxx/tddt/gui/scenes	line 29	Java Problem

**Comment by xxxFourierxxx** [comment]
Btw: How to find missing Javadoc in Eclipse:
Right click on your project:
Properties ->
Java Compiler ->
Javadoc ->
Project specifid settings

Then simply enable the tick marks

**Comment by xxxFourierxxx** [comment]
Can anyone give an update how much is still missing? ... The core components are all documented though I think

**Comment by faweizz** [comment]
one package is left undocumented
