### ISSUE TITLE
Streamline GUI

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#55]
make sure "back" buttons are all at the same location etc.

**Comment by Aranior** [comment]
Could not really change the .fxml file, which creates the back button for the statistics menu, someone else please do this.

**Comment by xxxFourierxxx** [comment]
@Tschebyscheff

**Comment by Aranior** [comment]
Yea i think we are done with this for now, I'm closing this issue
