### ISSUE TITLE
Manual: Various issues

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#56]
a) Missing description of "finaltests" in both student and teacher section. (final tests are hidden tests that check if the exercise is completed)
b)Missing description of XML format, how to enable babysteps, set timers etc.

**Comment by faweizz** [comment]
Missing description of "finaltests" student section. (final tests are hidden tests that check if the exercise is completed)

**Comment by Aranior** [comment]
I've added that section and fixed a few things, you can check if everything is fine if you want. But I think we might be done with the manual.
