### ISSUE TITLE
Issues in StatsPanel

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#57]
Re-Selecting an exercise adds the stats to the existing graphics.
Also TotalTime and keystrokes are not shown yet
When selecting an exercise for which no data is available some sort of popup  (AlertMessenger) should notify the user

**Comment by xxxFourierxxx** [comment]
![screenshot from 2016-07-13 17-27-16](https://cloud.githubusercontent.com/assets/19992332/16809030/15dce8ca-491f-11e6-8624-3be35c0235d9.png)
Also the bar graph should show all labels (stages) at any time

**Comment by Tschebyscheff** [comment]
there arent informations in stage refactor because tracking data got no errors for it

**Comment by xxxFourierxxx** [comment]
yes but the other two stages are not named whereas refactor is named (there is no label)

**Comment by Tschebyscheff** [comment]
nice, ty
