### ISSUE TITLE
The XML files have no influence on the exercises

### ISSUE THREAD

**Issue by faweizz** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#59]
why are these now serializable?!

**Comment by xxxFourierxxx** [comment]
what?

**Comment by faweizz** [comment]
nevermind, weve just got 2 dirs for them

**Comment by xxxFourierxxx** [comment]
the only one should be src/main/resources
this is because all other stuff is ignored when building and needs extra build script adjustments.
