### ISSUE TITLE
Extensive Beta Testing

### ISSUE THREAD

**Issue by xxxFourierxxx** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#61]
Now go and use our glorious software, try to break it and report all the issues you can still find

**Comment by xxxFourierxxx** [comment]
guess we ... tested ... a lot? ^^

**Comment by Aranior** [comment]
I literally left nothing untested!

**Comment by faweizz** [comment]
i also tried so hard 2 break it 

but it only got me so far

..sorry

**Comment by xxxFourierxxx** [comment]
ok lets close this
