### ISSUE TITLE
cant master RomanNumber

### ISSUE THREAD

**Issue by Tschebyscheff** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#64]
my code:
public class RomanNumberConverter 
{
	public static String convert(int i)
	{
		return "I";
	}
}
	
import static org.junit.Assert.*;
import org.junit.Test;
public class RomanNumberConverterTest 
{
	@Test
	public static void testSomething() 
	{
		assertEquals(RomanNumberConverter.convert(1), "I");	}
}
	
im tired maybe i did something wrong?

**Comment by xxxFourierxxx** [comment]
i'll check ... sec

**Comment by xxxFourierxxx** [comment]
Confirmed
