### ISSUE TITLE
opinion about unused tests

### ISSUE THREAD

**Issue by Tschebyscheff** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#67]
Whats your opinion about it? i think we shouldnt delete them cause of: "Sie müssen Ihr Programm nicht testgetrieben entwickeln, es soll aber ausreichend mit Unit-Tests abgedeckt werden."
So we have at least something.

**Comment by faweizz** [comment]
i would stay we can keep them

**Comment by xxxFourierxxx** [comment]
well depends, if they are dumb but working lets keep them but if the tests are just empty classes without tests they are not tests ^^ so i would delete those

**Comment by Tschebyscheff** [comment]
until now, i deleted empty test classes, the qustion is if we keep test classes that are enclosed with /* */

**Comment by xxxFourierxxx** [comment]
those simply need to be fixed by ... someone ... at ValveTime SoonTM
