### ISSUE TITLE
Vorstellen des Projekts

### ISSUE THREAD

**Issue by bendisposto** [ProPra16/programmierpraktikum-abschlussprojekt-xxxmathxxx#68]
ich würde euch bitten, euere Projekt in der Vorlesung am Donnerstag kurz (max. 10 min) vorzustellen.

**Comment by phspo** [comment]
Joah klar können wir machen, in welchem Rahmen denn? Muss jeder einen Teil vorstellen, ist das Programm irgendwo zum Zeigen auf einem Rechner bzw. mit Beamer an der Wand? Sollen wir den Code erläutern oder einfach nur mal das Programm zeigen?

**Comment by bendisposto** [comment]
10 Minuten sind etwas eng für ein Code Review. Ich kann das Programm gerne auf meinen Rechner packen und wenn ihr slides machen wollt kann ich die auch auf meinem Rechner zeigen.

**Comment by phspo** [comment]
Wir könnten auch einfach einen Rechner von uns mitbringen, das hätte den 
Vorteil, dass da dann schon ein paar Profile angelegt wären mit 
Beispielstatistiken, ist aber im Grunde egal.

Welche Anschlüsse hat denn der Beamer?

**Comment by bendisposto** [comment]
VGA, wenn es ein eigener Rechner ist, sollten wir das vor der VL kurz antesten

**Comment by phspo** [comment]
Ok, geht klar

**Comment by Aranior** [comment]
Guess we are done!

**Comment by bendisposto** [comment]
Ich habe einen blaues Ringbuch auf dem Tisch im HS gefunden, gehört das einem von euch?
